const lib = @import("lib.zig");
const spv = lib.spv;

pub const SourceLanguage = enum(u32) {
    Unknown = 0,
    ESSL = 1,
    GLSL = 2,
    OpenCL_C = 3,
    OpenCL_CPP = 4,
    HLSL = 5,
    CPP_for_OpenCL = 6,
    SYCL = 7,
    HERO_C = 8,
    NZSL = 9,
    WGSL = 10,
    Slang = 11,
    Zig = 12,
    Rust = 13,
};

pub fn vendorName(id: u32) []const u8 {
    return switch (id) {
        0 => "Khronos",
        1 => "LunarG",
        2 => "Valve",
        3 => "Codeplay",
        4 => "NVIDIA",
        5 => "ARM",
        6 => "Khronos LLVM/SPIR-V Translator",
        7 => "Khronos SPIR-V Tools Assembler",
        8 => "Khronos Glslang Reference Front End",
        9 => "Qualcomm",
        10 => "AMD",
        11 => "Intel",
        12 => "Imagination",
        13 => "Google Shaderc over Glslang",
        14 => "Google spiregg",
        15 => "Google rspirv",
        16 => "X-LEGEND Mesa-IR/SPIR-V Translator",
        17 => "Khronos SPIR-V Tools Linker",
        18 => "Wine VKD3D Shader Compiler",
        19 => "Tellusim Clay Shader Compiler",
        20 => "W3C WebGPU Group WHLSL Shader Translator",
        21 => "Google Clspv",
        22 => "LLVM MLIR SPIR-V Serializer",
        23 => "Google Tint Compiler",
        24 => "Google ANGLE Shader Compiler",
        25 => "Netease Games Messiah Shader Compiler",
        26 => "Xenia Xenia Emulator Microcode Translator",
        27 => "Embark Studios Rust GPU Compiler Backend",
        28 => "gfx-rs community Naga",
        29 => "Mikkosoft Productions MSP Shader Compiler",
        30 => "SpvGenTwo community SpvGenTwo SPIR-V IR Tools",
        31 => "Google Skia SkSL",
        32 => "TornadoVM Beehive SPIRV Toolkit",
        33 => "DragonJoker ShaderWriter",
        34 => "Rayan Hatout SPIRVSmith",
        35 => "Saarland University Shady",
        36 => "Taichi Graphics Taichi",
        37 => "heroseh Hero C Compiler",
        38 => "Meta SparkSL",
        39 => "SirLynix Nazara ShaderLang Compiler",
        40 => "Khronos Slang Compiler",
        41 => "Zig Software Foundation Zig Compiler",
        42 => "Rendong Liang spq",
        43 => "LLVM LLVM SPIR-V Backend",
        44 => "Robert Konrad Kongruent",
        45 => "Kitsunebi Games Nuvk SPIR-V Emitter and DLSL compiler",
        46 => "Nintendo",
        47 => "ARM",
        48 => "Goopax",
        49 => "Icyllis Milica Arc3D Shader Compiler",

        else => "Unknown",
    };
}
